### ISSUE TITLE
macOS: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by djlawhead** [sqweek/dialog#1]
Looks like a new way in which Go passes pointers to C/C++/ObjC breaks the file dialogue open call on macOS.

Specific line:
cocoa/dlg.go:77

More information:
https://github.com/ry/v8worker/issues/31

**Comment by sqweek** [comment]
Ah yep, I'm familiar with that go 1.6 change. Thanks for the heads up, I'll take a look when I get some spare cycles.

**Comment by sqweek** [comment]
That oughta do it, merry christmas :)

**Comment by djlawhead** [comment]
Thanks man!!
