### ISSUE TITLE
Feature: Add possibility to pre-define filename

### ISSUE THREAD

**Issue by Torbilicious** [sqweek/dialog#26]
Would it be possible to add functionality to define a recommended filename for the save dialog?

Currently on mac it defaults to Undefined and on windows it is just empty.

**Comment by sqweek** [comment]
Do you mean "Untitled" on mac, or are you actually seeing "Undefined"?

Seems like a reasonable feature either way :)

**Comment by sqweek** [comment]
This has been implemented in #66 (thanks redraskal!)
