### ISSUE TITLE
GTK3

### ISSUE THREAD

**Issue by matteosuppo** [sqweek/dialog#4]
I'd love to use this but my app already uses gtk3. Do you think I should make a pull request here or I would be better forking it?

**Comment by sqweek** [comment]
You're using gtk3 on linux only?

Ideally dialog wouldn't depend on any gtk but writing a whole new file browser sounds like a separate project :)

It would certainly be an improvement to be able to depend on gtk2 OR gtk3 (or other toolkits), but I'm not quite sure how to orchestrate that without requiring additional imports and I don't want to complicate things for the primary use case (ie. users that just want a dialog and don't care about the toolkit). I feel like gtk2 remains more common on linux distros so I don't love the idea of switching to gtk3 by default either -- probably forking will get you up and running faster.

**Comment by meskio** [comment]
I agree having support for both 2 and 3 will be too cumbersome. I think gtk3 is more and more ubiquitous and might make sense to migrate the dialog library.

Anyway, I'm playing around with a fork of this library to gtk3:
https://github.com/meskio/dialog/tree/gtk3

**Comment by anarcat** [comment]
> It would certainly be an improvement to be able to depend on gtk2 OR gtk3 (or other toolkits), but I'm not quite sure how to orchestrate that without requiring additional imports and I don't want to complicate things for the primary use case (ie. users that just want a dialog and don't care about the toolkit). I feel like gtk2 remains more common on linux distros so I don't love the idea of switching to gtk3 by default either -- probably forking will get you up and running faster.

At this point, I would argue that GTK2 is on its way out and GTK3 is *definitely* available everywhere. Therefore, GTK3 is *more* common than GTK2 and I would suggest switching.

Would you be open to that? It seems code that does that is available and running in production here:

**Comment by anarcat** [comment]
Besides, nothing keeps you from leaving GTK2 support in an older branch: dependencies could still use that, using proper go tooling, which I believe might be fairly easy to do...

**Comment by sqweek** [comment]
Well there seems to be a growing consensus; probably the person it's going to annoy the most is me and I'm not regularly using linux these days so I don't really count :P
I'll aim to find some time to look at the changes over the next week -- if there's anyone who objects to dropping gtk2 from mainline please speak up.

**Comment by sqweek** [comment]
Thanks all for the feedback. I've switched over to gtk3.
