### ISSUE TITLE
GTK/Pango affecting Gitlab workflow

### ISSUE THREAD

**Issue by bconn98** [sqweek/dialog#53]
Hello,

While setting up my projects Github Workflows, I ran into an issue with your library which I would like to continue using if at all possible. The go get command was unable to located the pango library. I resolved the pipeline by removing the use of your code but as I said I would like to keep it if possible. I see that you removed pango regarding other issues so I am hoping you are able to find a solution to this.

Failed pipeline with dialog - https://github.com/bconn98/DrugRecord/runs/1308636059?check_suite_focus=true

Successful pipeline withou dialog - https://github.com/bconn98/DrugRecord/runs/1306842166?check_suite_focus=true

**Comment by sqweek** [comment]
The log suggests to me that gtk+-3.0 is missing, although gtk itself does of course depend on pango. On linux the gtk library is a hard dependency for dialog, and that's unlikely to change.

**Comment by bconn98** [comment]
Update, this appears to have been resolved.
