### ISSUE TITLE
Message can not to show

### ISSUE THREAD

**Issue by whimthen** [sqweek/dialog#54]
```go
ok := dialog.Message("%s", "Do you want to continue?").Title("Are you sure?").YesNo()
log.Println(ok)
```

The code is like this, sometimes the Message cannot be displayed, sometimes it can be displayed, and the program is blocked when it is not displayed.

I write code on macOS, version: 11.0.1

But File and Directory can work normally.

**Comment by faruqisan** [comment]
Use this [library](https://github.com/gen2brain/dlgs), it works on macOS Cataline

**Comment by whimthen** [comment]
> Use this [library](https://github.com/gen2brain/dlgs), it works on macOS Cataline

OK, thanks.
