### ISSUE TITLE
Package gtk+-3.0 was not found...

### ISSUE THREAD

**Issue by cydside** [sqweek/dialog#56]
Hi, I just run  `go run main.go` on the package example `dialog/example/simple/main.go` receiving the following messages:<br />

pkg-config --cflags  -- gtk+-3.0  
Package gtk+-3.0 was not found in the pkg-config search path.  
Perhaps you should add the directory containing gtk+-3.0.pc  
to the PKG_CONFIG_PATH environment variable  
No package 'gtk+-3.0' found  
pkg-config: exit status 1  

On a Linux Mint amd64 machine with libgtk-3-0 already updated to (3.22.30-1ubuntu4).
Could you please suggest a solution?

**Comment by sqweek** [comment]
You're missing the development files for libgtk-3. In ubuntu they come in a separate package `libgtk-3-dev`.

Note that you will always need the -dev package when you're compiling code against a library.
