### ISSUE TITLE
Pipeline is Failing

### ISSUE THREAD

**Issue by vinodsharmak** [sqweek/dialog#62]
Build and test are working fine on windows machine but pipeline is failing on linux. Please suggest if there are any dependencies we have to download. Pipeline logs are

Unable to init server: Could not connect: Connection refused
(cpaas.test:225111): Gtk-WARNING **: 14:34:32.673: cannot open display:

go: downloading github.com/sqweek/dialog v0.0.0-20211002065838-9a201b55ab91
?   	bitbucket.org/gath3rio/cpaas-desktop-file-transfer/pkg/config	[no test files]
Unable to init server: Could not connect: Connection refused
(cpaas.test:224311): Gtk-WARNING **: 14:31:47.868: cannot open display:

pkg-config --modversion gtk+-3.0
3.22.11

Thanks

**Comment by sqweek** [comment]
Your pipeline environment doesn’t have an X server running so cannot display any dialogs.

**Comment by lexxxel** [comment]
@sqweek but this means, I can NOT run any unit test on my project because the import of `dialog` will trigger
```golang
 C.XInitThreads()
 C.gtk_init(nil, nil)
```
without any chance to 'disable' that. I mean, what would you think about some kind of variable (like env variable) that is checked before triggering `gtk_init`?

**Comment by sqweek** [comment]
@lexxxel ok it is reasonable to avoid gtk exiting during go init() when run in a headless context. I've made a change to that effect, however dialog will still panic if the app tries to open any dialogs (I'm not really interested in adding complexity for graceful degradation in headless contexts; dialog is a graphics package first and foremost).
