### ISSUE TITLE
Windows 11: FileOpen filter extensions not working?

### ISSUE THREAD

**Issue by dweymouth** [sqweek/dialog#77]
It seems that setting an extensions filter in a ~~FileSave~~ FileOpen dialog is not working on Windows 11? The dialog is allowing the user to select any file. The same code works fine on MacOS so I don't believe it's a bug on my end

**Comment by roffe** [comment]
I use file open dialog on Windows 11 without problems

**Comment by dweymouth** [comment]
Never mind, I needed to set the Description along with the Extensions
