### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tmm1** [sqweek/dialog#8]
Hi, under what license is this project published?

**Comment by sqweek** [comment]
Hiya! Sorry for the delay. I intend to publish this under the [ISC license](https://en.wikipedia.org/wiki/ISC_license) - here's my proposed patch: 3468251cc2a8cbc0d07362e01be2f28cdfbe8364

@patrickgh3 @juliardi @Schobers You've all contributed code prior to the license being clarified, can you please let me know whether ISC is acceptable for you or not?

**Comment by juliardi** [comment]
Yes, it is alright for me

**Comment by Schobers** [comment]
No problem for me.

**Comment by patrickgh3** [comment]
Sure!

**Comment by sqweek** [comment]
Thanks folks! Turns out I accidentally pushed the license when fixing #12 last night so this is resolved now :)
